### ISSUE TITLE
登入授权报错

### ISSUE THREAD

**Issue by kkkyg** [GGttyyy/Euserv_extend_pin#1]
网页提示：localhost 拒绝了我们的连接请求

**Comment by GGttyyy** [comment]
Oauth 同意屏幕 如果选的测试版，需要手动添加测试用户。
凭据 - OAuth 2.0 client 设置 重定向url为http://localhost:36666/

**Comment by kkkyg** [comment]
> 首次，需要在本地电脑上运行，获取token文件。 Oauth 同意屏幕 如果选的测试版，需要手动添加测试用户，要么就发布应用. 凭据 - OAuth 2.0 client 设置 重定向url为http://localhost:36666/

是用VPS在电脑上的SSH端上运行的，Oauth 同意屏幕设置没问题，只设了重定向ur也没问题。下载重命名的credentials.json也有，在VPS上python3 gmail_api.py email1出来的链接，在谷歌浏览器上也有看到程序同意授权查看GMAIL的提示，点同意就出现：
网页提示：localhost 拒绝了我们的连接请求

**Comment by GGttyyy** [comment]
> > 首次，需要在本地电脑上运行，获取token文件。 Oauth 同意屏幕 如果选的测试版，需要手动添加测试用户，要么就发布应用. 凭据 - OAuth 2.0 client 设置 重定向url为http://localhost:36666/
> 
> 是用VPS在电脑上的SSH端上运行的，Oauth 同意屏幕设置没问题，只设了重定向ur也没问题。下载重命名的credentials.json也有，在VPS上python3 gmail_api.py email1出来的链接（此时SSH界面是卡住的） 链接地址：https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=361166972604-g7f3d0n012nvhqca8einphfofgr91u20.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A36666%2F&scope=https%3A%2F%2Fmail.google.com%2F&state=CxZunAtndiy3sNoYNdlnPnLMuLZlLT&access_type=offline ，此链接在电脑谷歌浏览器上也有看到程序同意授权查看gmail的提示，点同意就出现： 网页提示：localhost 拒绝了我们的连接请求

首次运行脚本需要本地运行，和浏览器授权同一台机器下运行。运行完生成token文件,自行上传到vps

**Comment by kkkyg** [comment]
浏览器提示：
The authentication flow has completed. You may close this window.

但同时PY界面提示如下，好像还是失败了。。。
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\1\gmail_api.py", line 53, in <module>
    service = gmail_authenticate(userId)
  File "c:\1\gmail_api.py", line 30, in gmail_authenticate
    creds = flow.run_local_server(port=36666)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\google_auth_oauthlib\flow.py", line 477, in run_local_server
    self.fetch_token(authorization_response=authorization_response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\google_auth_oauthlib\flow.py", line 286, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_oauthlib\oauth2_session.py", line 336, in fetch_token
    r = self.request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_oauthlib\oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

**Comment by GGttyyy** [comment]
全局科学上网，或者设置代理。
